# Generated by Django 3.0.2 on 2020-01-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
