# Generated by Django 3.0.2 on 2020-04-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0004_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
