# Generated by Django 3.0.2 on 2020-05-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0006_auto_20200406_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('residence_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='residences.Residence')),
            ],
        ),
    ]
