# Generated by Django 3.0.2 on 2020-07-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0009_auto_20200515_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='coords',
            field=models.IntegerField(default=1),
        ),
    ]
