# Generated by Django 3.0.2 on 2020-07-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0010_residence_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='coords',
        ),
    ]
