# Generated by Django 3.0.2 on 2020-07-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0011_remove_residence_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='residence',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
