# Generated by Django 3.0.2 on 2020-07-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0012_auto_20200726_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='residence',
            name='lon',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
