# Generated by Django 3.0.2 on 2020-08-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0013_auto_20200730_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='residence',
            name='lon',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
