# Generated by Django 3.0.2 on 2020-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0014_auto_20200802_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='residence',
            name='lon',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
        ),
    ]
